name: clean_store_app
description: A clean architecture store application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  flutter_riverpod: ^2.4.9
  # Navigation
  curved_navigation_bar: ^1.0.6
  # Dependency injection
  get_it: ^7.6.4
  # Data class generation
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  # JSON serialization
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  http: ^1.2.2
  mqtt_client: ^10.5.1
  image_picker: ^1.0.7
  package_info_plus: ^8.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
