name: smart_gate_new_version
description: "A new Flutter project."
publish_to: "none"
version: 1.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Navigation
  curved_navigation_bar: ^1.0.6
  # Dependency injection
  get_it: ^7.6.4
  # Data class generation
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  # JSON serialization
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  http: ^1.2.2
  mqtt_client: ^10.5.1
  image_picker: ^1.0.7
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true # Enable generation of localization files

  assets:
    - lib/assets/icons/logo/CHP_logo.png
    - lib/assets/icons/logo/CHP_logo.jpg
    - lib/assets/icons/logo/htit-logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/logo/htit-logo.png"
